meta_product_name: "Balancer"
meta_title: "Balancer - listening to the voice of underrepresented entrepreneurs"
meta_description: "Impact investing platform for underrepresented
                  people, where creators showcase their ideas and investors
                  can browse and fund them. This will put a spotlight
                  on women and POC creators + give power to perspectives
                  that are systematically overlooked. Time to level the playing field"
meta_image: "meta_img_bg_buswoman.png"
